services:
  - type: web
    name: hoiku-navi
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hoiku_navi.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"