# Generated by Django 4.2.10 on 2025-08-20 03:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_number', models.CharField(max_length=20, unique=True, verbose_name='施設番号')),
                ('name', models.CharField(max_length=100, verbose_name='保育園名')),
                ('nursery_type', models.CharField(choices=[('認可保育園', '認可保育園'), ('認証保育園', '認証保育園'), ('無認可保育園', '無認可保育園'), ('幼稚園', '幼稚園'), ('認定こども園', '認定こども園'), ('小規模保育', '小規模保育'), ('企業主導型保育', '企業主導型保育')], max_length=20, verbose_name='施設タイプ')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号は数字とハイフンのみで入力してください', regex='^[0-9-]+$')], verbose_name='電話番号')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='開園時間')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='閉園時間')),
                ('saturday_available', models.BooleanField(default=False, verbose_name='土曜保育')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='定員')),
                ('age_from_months', models.IntegerField(blank=True, help_text='何ヶ月から', null=True, verbose_name='受入開始月齢')),
                ('age_to_years', models.IntegerField(blank=True, help_text='何歳まで', null=True, verbose_name='受入終了年齢')),
                ('has_contact_app', models.BooleanField(default=False, verbose_name='連絡帳アプリ有無')),
                ('contact_app_name', models.CharField(blank=True, max_length=50, verbose_name='連絡帳アプリ名')),
                ('has_school_bus', models.BooleanField(default=False, verbose_name='送迎バス')),
                ('has_parking', models.BooleanField(default=False, verbose_name='駐車場')),
                ('has_lunch', models.BooleanField(default=True, verbose_name='給食')),
                ('has_allergy_support', models.BooleanField(default=False, verbose_name='アレルギー対応')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='経度')),
                ('distance_from_home', models.FloatField(blank=True, null=True, verbose_name='自宅からの距離(km)')),
                ('travel_time', models.IntegerField(blank=True, null=True, verbose_name='自宅からの所要時間(分)')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '保育園',
                'verbose_name_plural': '保育園',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='見学日')),
                ('visit_time', models.TimeField(blank=True, null=True, verbose_name='見学時間')),
                ('status', models.CharField(choices=[('予定', '予定'), ('完了', '完了'), ('キャンセル', 'キャンセル')], default='予定', max_length=10, verbose_name='ステータス')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='担当者名')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_schedules', to='nursery.nursery', verbose_name='保育園')),
            ],
            options={
                'verbose_name': '見学スケジュール',
                'verbose_name_plural': '見学スケジュール',
                'ordering': ['visit_date', 'visit_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')], verbose_name='総合評価')),
                ('facility_rating', models.IntegerField(blank=True, choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')], null=True, verbose_name='施設・設備')),
                ('staff_rating', models.IntegerField(blank=True, choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')], null=True, verbose_name='スタッフ・先生')),
                ('education_rating', models.IntegerField(blank=True, choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')], null=True, verbose_name='教育方針')),
                ('access_rating', models.IntegerField(blank=True, choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')], null=True, verbose_name='アクセス')),
                ('good_points', models.TextField(verbose_name='良かった点')),
                ('concern_points', models.TextField(blank=True, verbose_name='気になった点')),
                ('staff_impression', models.TextField(blank=True, verbose_name='スタッフの印象')),
                ('children_atmosphere', models.TextField(blank=True, verbose_name='子どもたちの様子')),
                ('estimated_monthly_fee', models.IntegerField(blank=True, null=True, verbose_name='想定月額費用(円)')),
                ('application_intention', models.BooleanField(default=False, verbose_name='申込意向')),
                ('priority_rank', models.IntegerField(blank=True, null=True, verbose_name='優先順位')),
                ('photo1', models.ImageField(blank=True, upload_to='visit_photos/', verbose_name='写真1')),
                ('photo2', models.ImageField(blank=True, upload_to='visit_photos/', verbose_name='写真2')),
                ('photo3', models.ImageField(blank=True, upload_to='visit_photos/', verbose_name='写真3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='nursery.nursery', verbose_name='保育園')),
                ('visit_schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impression', to='nursery.visitschedule', verbose_name='見学スケジュール')),
            ],
            options={
                'verbose_name': '見学感想',
                'verbose_name_plural': '見学感想',
                'ordering': ['-created_at'],
            },
        ),
    ]
